[build]
  command = "bash build.sh"
  publish = "build/html"

[build.environment]
  CARGO_HOME = "/opt/build/repo/.cargo"
  RUSTUP_HOME = "/opt/build/repo/.rustup"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [
      ".cargo",
      ".rustup",
      ".rheo-binary"
    ]
